### ISSUE TITLE
Some find IDs have disappeared from the csv result

### ISSUE THREAD

**Issue by leemordechai** [pyzmark/FLAME_DAI_transformation#4] opened 2023-05-28 10:27 UTC
See the image for some of the listed find IDs. e.g. #2405 is missing. 

![image](https://github.com/pyzmark/FLAME_DAI_transformation/assets/16713928/c034ecc4-0f25-4fe4-89a9-6d5c06a7956f)

**Comment by pyzmark** [comment] 2023-06-09 18:02
The problem is that the DAI never assigned the lost finds (e.g., 2405) a find category. It's caused them to silently fall out of the new 'finds' df that we cobbled together from the 'daip' raw data. I am going to build in a conditional or some kind of work around to make sure that they just receive null values for this field, but remain in the resulting df.

**Comment by pyzmark** [comment] 2023-06-09 22:30
A new export has been uploaded that restores these finds. If you can check and confirm, we can close the issue.

**Comment by pyzmark** [comment] 2023-06-12 16:24
This is in the new commit. Closing. Let me know if we need to reopen.

**Closed as completed by pyzmark** 2023-06-12 16:24 UTC
Labels: needs confirmation
